version: "3"

services:
  datasource:
      image: postgres:alpine
      restart: always
      environment:
        - POSTGRES_DB=datasource
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./sql/data/postgres:/var/lib/postgresql/data
  web:
    image: rscheele3214/rego_builder
    ports:
      - "8080:8080"
    env_file:
      - .env