version: "3"

services:
  datasource:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datasource
    volumes:
      - ./sql/data/postgres:/var/lib/postgresql/data
  web:
    image: rscheele3214/rego_builder
    ports:
      - "8080:8080"
    env_file:
      - .env