version: "3"

services:
  datasource:
      image: postgres:alpine
      environment:
        - POSTGRES_DB=datasource
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5433:5432'
      volumes:
        - ./sql/data/postgres:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/rego_builder:ro
    env_file:
      - .env

        
 
