version: "3.8"

services:
  datasource:
      image: postgres:alpine
      ports:
        - '5432:5432'
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - ./sql/data/postgres:/var/lib/postgresql/data
        - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_tables.sql
      networks:
        - default

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/rego_builder:ro
    env_file:
      - .env
    restart: always
    depends_on:
      - datasource
    links:
      - datasource
    
 
