# This workflow will install Python dependencies, lint using Black, run tests using Pytest 
name: Code quality check and endpoint test workflow

on: 
  #Trigger the workflow on a push/pull_requests event to the main branch only
  push: 
    branches: [main]
  pull_request:
    branches: [main]

# A workflow job running sequentially
jobs:
  build:
    # runs-on: defines The workflow runner
    runs-on: ubuntu-latest 
    # steps: defines a series of tasks executed by the Job
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2.3.0
        
        with:
          python-version: "3.10"


      - run: pip install --upgrade pip
      - run: pip install black pytest
      - run: black .
      - run: pytest .
