
# This workflow will install Python dependencies, lint using Black, run tests using Pytest 
name: rego_builder github workflow

on: 
  #Trigger the workflow on a push/pull_requests event to the main branch only
  push: 
    branches: [main]
  pull_request:
    branches: [main]

# A workflow job running sequentially
jobs:
  build:
    # runs-on: defines The workflow runner
    runs-on: ubuntu-latest 
    # steps: defines a series of tasks executed by the Job

    defaults:
      run:
        working-directory: /rego_builder
    
    steps:
    #Task for setting up Python 3.10 using actions/setup-python@v2 Github action
      - name: Set up Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: "3.10"
    
      - name: Format code
        working-directory: ./app
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      # - run: pip install --upgrade pip
      # - run: pip install pytest
      # - run: pytest


    